export const GET_BURGER_INGREDIENTS: "GET_BURGER_INGREDIENTS" = "GET_BURGER_INGREDIENTS";
export const GET_BURGER_INGREDIENTS_SUCCESS: "GET_BURGER_INGREDIENTS_SUCCESS" = "GET_BURGER_INGREDIENTS_SUCCESS";
export const GET_BURGER_INGREDIENTS_FAILED: "GET_BURGER_INGREDIENTS_FAILED" = "GET_BURGER_INGREDIENTS_FAILED";