export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT: "REMOVE_INGREDIENT" = "REMOVE_INGREDIENT"
export const MOVE_INGREDIENT: "MOVE_INGREDIENT" = "MOVE_INGREDIENT"
export const CLEAN_CONSTRUCTOR: "CLEAN_CONSTRUCTOR" = "CLEAN_CONSTRUCTOR"

export const GET_BURGER_INGREDIENTS: "GET_BURGER_INGREDIENTS" = "GET_BURGER_INGREDIENTS";
export const GET_BURGER_INGREDIENTS_SUCCESS: "GET_BURGER_INGREDIENTS_SUCCESS" = "GET_BURGER_INGREDIENTS_SUCCESS";
export const GET_BURGER_INGREDIENTS_FAILED: "GET_BURGER_INGREDIENTS_FAILED" = "GET_BURGER_INGREDIENTS_FAILED";

export const GET_TOKEN: "GET_TOKEN_CODE" = "GET_TOKEN_CODE";
export const GET_TOKEN_SUCCESS: "GET_TOKEN_SUCCESS" = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILED: "GET_TOKEN_FAILED" = "GET_TOKEN_FAILED";
export const GET_TOKEN_CLEAN_STATE: "GET_TOKEN_CLEAN_STATE" = "GET_TOKEN_CLEAN_STATE"

export const USER_LOGIN: "USER_LOGIN" = "USER_LOGIN";
export const USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS" = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED: "USER_LOGIN_FAILED" = "USER_LOGIN_FAILED";

export const LOG_OUT: "LOG_OUT" = "LOG_OUT";
export const LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS" = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILED: "LOG_OUT_FAILED" = "LOG_OUT_FAILED";

export const SEND_ORDER: "SEND_ORDER" = "SEND_ORDER";
export const SEND_ORDER_SUCCESS: "SEND_ORDER_SUCCESS" = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_FAILED: "SEND_ORDER_FAILED" = "SEND_ORDER_FAILED";
export const HIDE_ORDER: "HIDE_ORDER" = "HIDE_ORDER"

export const PASSWORD_RESET: "PASSWORD_RESET" = "PASSWORD_RESET";
export const PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS" = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED" = "PASSWORD_RESET_FAILED";
export const PASSWORD_RESET_CLEAN_STATE: "PASSWORD_RESET_CLEAN_STATE" = "PASSWORD_RESET_CLEAN_STATE";

export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED = "GET_USER_INFO_FAILED";
export const CLEAN_USER_INFO = "CLEAN_USER_INFO";

export const REFRESH_USER_INFO: "REFRESH_USER_INFO" = "REFRESH_USER_INFO";
export const REFRESH_USER_INFO_SUCCESS: "REFRESH_USER_INFO_SUCCESS" = "REFRESH_USER_INFO_SUCCESS";
export const REFRESH_USER_INFO_FAILED: "REFRESH_USER_INFO_FAILED" = "REFRESH_USER_INFO_FAILED";

export const USER_REGISTER: "USER_REGISTER" = "USER_REGISTER";
export const USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS" = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED: "USER_REGISTER_FAILED" = "USER_REGISTER_FAILED";
export const REGISTER_CLEAN_STATE: "REGISTER_CLEAN_STATE" = "REGISTER_CLEAN_STATE";

export const ORDER_FEED_START: 'ORDER_FEED_START' = 'ORDER_FEED_START';
export const ORDER_FEED_SUCCESS: 'ORDER_FEED_SUCCESS' = 'ORDER_FEED_SUCCESS';
export const ORDER_FEED_ERROR: 'ORDER_FEED_ERROR' = 'ORDER_FEED_ERROR';
export const ORDER_FEED_CLOSED: 'ORDER_FEED_CLOSED' = 'ORDER_FEED_CLOSED';
export const ORDER_FEED_CLOSE: 'ORDER_FEED_CLOSE' = 'ORDER_FEED_CLOSE'
export const ORDER_FEED_GET_MESSAGE: 'ORDER_FEED_GET_MESSAGE' = 'ORDER_FEED_GET_MESSAGE';

export const ORDER_HISTORY_START: 'ORDER_HISTORY_START' = 'ORDER_HISTORY_START';
export const ORDER_HISTORY_SUCCESS: 'ORDER_HISTORY_SUCCESS' = 'ORDER_HISTORY_SUCCESS';
export const ORDER_HISTORY_ERROR: 'ORDER_HISTORY_ERROR' = 'ORDER_HISTORY_ERROR';
export const ORDER_HISTORY_CLOSED: 'ORDER_HISTORY_CLOSED' = 'ORDER_HISTORY_CLOSED';
export const ORDER_HISTORY_CLOSE: 'ORDER_HISTORY_CLOSE' = 'ORDER_HISTORY_CLOSE'
export const ORDER_HISTORY_GET_MESSAGE: 'ORDER_HISTORY_GET_MESSAGE' = 'ORDER_HISTORY_GET_MESSAGE';