export const SEND_ORDER: "SEND_ORDER" = "SEND_ORDER";
export const SEND_ORDER_SUCCESS: "SEND_ORDER_SUCCESS" = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_FAILED: "SEND_ORDER_FAILED" = "SEND_ORDER_FAILED";
export const HIDE_ORDER: "HIDE_ORDER" = "HIDE_ORDER"