export const PASSWORD_RESET: "PASSWORD_RESET" = "PASSWORD_RESET";
export const PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS" = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED" = "PASSWORD_RESET_FAILED";
export const PASSWORD_RESET_CLEAN_STATE: "PASSWORD_RESET_CLEAN_STATE" = "PASSWORD_RESET_CLEAN_STATE";